const archiveItems = [
  {
    "id": "hks-0842-lax-med",
    "archiveCode": "HKS-0842-LAX-MED",
    "title": "Lattice Vault Study",
    "location": "Los Angeles, USA",
    "locationCode": "LAX-MED",
    "typology": "Medical / Research Facility",
    "prototypeType": "3D Concrete Printing",
    "material": "Ultra-High-Performance Concrete",
    "fabricationMethod": "Large-Scale Robotic Extrusion",
    "projectPhase": "Design Development Study",
    "description": "The fabrication sequence explores continuous extrusion for structural lattice components, testing joinery tolerances and material behavior during cure.",
    "introduction": "A study examining continuous material extrusion for structural lattice components in campus environments, exploring geometric optimization and cure-time management.",
    "accessionNumber": "ARCH.2021.0842.03",
    "orbitCenterId": "center-fabrication",
    "year": 2021,
    "orbitRadius": 190,
    "orbitAngleDeg": -18,
    "importance": 5
  },
  {
    "id": "hks-0217-dfw-spt",
    "archiveCode": "HKS-0217-DFW-SPT",
    "title": "Stadium Canopy Stress Model",
    "location": "Dallas, USA",
    "locationCode": "DFW-SPT",
    "typology": "Sports Venue",
    "prototypeType": "3D-Printed Structural Model",
    "material": "PLA Composite",
    "fabricationMethod": "FDM Additive Print",
    "projectPhase": "Prototype (TRL-4)",
    "description": "A reduced-scale canopy assembly used to validate wind-load stress simulation results against a physical structural analogue.",
    "introduction": "Stress simulation study for a cantilevered stadium canopy, printed at reduced scale to correlate digital load models with physical deflection.",
    "accessionNumber": "ARCH.2021.0217.02",
    "orbitCenterId": "center-fabrication",
    "year": 2021,
    "orbitRadius": 120,
    "orbitAngleDeg": -55,
    "importance": 4
  },
  {
    "id": "hks-1093-sfo-cmx",
    "archiveCode": "HKS-1093-SFO-CMX",
    "title": "Reclaimed Cladding Weathering Panel",
    "location": "San Francisco, USA",
    "locationCode": "SFO-CMX",
    "typology": "Mixed-Use",
    "prototypeType": "Material Test",
    "material": "Reclaimed Timber",
    "fabricationMethod": "CNC Milling",
    "projectPhase": "Field Trial",
    "description": "A weathering panel exposed to coastal conditions over eighteen months to record surface degradation of reclaimed facade timber.",
    "introduction": "Long-duration exposure test tracking how reclaimed timber cladding weathers under coastal marine conditions.",
    "accessionNumber": "ARCH.2019.1093.01",
    "orbitCenterId": "center-fabrication",
    "year": 2019,
    "orbitRadius": 280,
    "orbitAngleDeg": 8,
    "importance": 3
  },
  {
    "id": "hks-0371-nyc-hos",
    "archiveCode": "HKS-0371-NYC-HOS",
    "title": "Stone Cladding Connection Detail",
    "location": "New York, USA",
    "locationCode": "NYC-HOS",
    "typology": "Hospitality",
    "prototypeType": "Construction Mockup",
    "material": "Limestone Composite",
    "fabricationMethod": "CNC Stone Routing",
    "projectPhase": "Prototype (TRL-6)",
    "description": "Full-scale construction mockup verifying a concealed anchoring detail for a ventilated stone rainscreen.",
    "introduction": "A detailed study of stone cladding connections for a hospitality tower facade, focused on thermal movement and concealed fixings.",
    "accessionNumber": "ARCH.2017.0371.04",
    "orbitCenterId": "center-fabrication",
    "year": 2017,
    "orbitRadius": 340,
    "orbitAngleDeg": 32,
    "importance": 4
  },
  {
    "id": "hks-0658-sea-edu",
    "archiveCode": "HKS-0658-SEA-EDU",
    "title": "Robotic Assembly Structure",
    "location": "Seattle, USA",
    "locationCode": "SEA-EDU",
    "typology": "Education",
    "prototypeType": "Experimental Fabrication Study",
    "material": "Timber / Steel Hybrid",
    "fabricationMethod": "Robotic Assembly",
    "projectPhase": "Prototype (TRL-6)",
    "description": "A robotically assembled timber-steel node system developed to test complex non-orthogonal geometries for an education building structure.",
    "introduction": "Robotic assembly study for complex geometry, developed for an education campus structural framing system.",
    "accessionNumber": "ARCH.2020.0658.05",
    "orbitCenterId": "center-fabrication",
    "year": 2020,
    "orbitRadius": 40,
    "orbitAngleDeg": 210,
    "importance": 5
  },
  {
    "id": "hks-0659-sea-edu",
    "archiveCode": "HKS-0659-SEA-EDU",
    "title": "Node Connector Iteration B",
    "location": "Seattle, USA",
    "locationCode": "SEA-EDU",
    "typology": "Education",
    "prototypeType": "Component Study",
    "material": "Cast Aluminum",
    "fabricationMethod": "Investment Casting",
    "projectPhase": "Prototype (TRL-4)",
    "description": "Second-iteration cast node connector reducing part count from the prior revision while maintaining load capacity.",
    "introduction": "Companion study to the robotic assembly structure, refining the cast connector geometry used at each structural node.",
    "accessionNumber": "ARCH.2020.0659.01",
    "orbitCenterId": "center-fabrication",
    "year": 2020,
    "orbitRadius": 130,
    "orbitAngleDeg": 250,
    "importance": 2
  },
  {
    "id": "hks-1215-ord-res",
    "archiveCode": "HKS-1215-ORD-RES",
    "title": "Formworkless Arch Structure",
    "location": "Chicago, USA",
    "locationCode": "ORD-RES",
    "typology": "Residential",
    "prototypeType": "Concrete-Printing Model",
    "material": "Fiber-Reinforced Concrete",
    "fabricationMethod": "Formworkless Printing",
    "projectPhase": "Design Development Study",
    "description": "A self-supporting arch geometry printed without temporary formwork, tuned to remain within the material\\u2019s green-state stability limits.",
    "introduction": "Exploration of formworkless printing for arched residential spans, minimizing material waste from temporary falsework.",
    "accessionNumber": "ARCH.2022.1215.02",
    "orbitCenterId": "center-fabrication",
    "year": 2022,
    "orbitRadius": 400,
    "orbitAngleDeg": 70,
    "importance": 3
  },
  {
    "id": "hks-0910-bos-lab",
    "archiveCode": "HKS-0910-BOS-LAB",
    "title": "Modular Lab Bench Prototype",
    "location": "Boston, USA",
    "locationCode": "BOS-LAB",
    "typology": "Research Facility",
    "prototypeType": "Furniture System",
    "material": "Powder-Coated Steel",
    "fabricationMethod": "Sheet Metal Fabrication",
    "projectPhase": "Prototype (TRL-6)",
    "description": "A reconfigurable lab bench frame designed for rapid utility reconnection between research building fit-outs.",
    "introduction": "Modular casework system developed for flexible laboratory environments requiring frequent reconfiguration.",
    "accessionNumber": "ARCH.2018.0910.01",
    "orbitCenterId": "center-fabrication",
    "year": 2018,
    "orbitRadius": 240,
    "orbitAngleDeg": -110,
    "importance": 2
  },
  {
    "id": "hks-0501-mia-cul",
    "archiveCode": "HKS-0501-MIA-CUL",
    "title": "Coral-Aggregate Concrete Sample",
    "location": "Miami, USA",
    "locationCode": "MIA-CUL",
    "typology": "Cultural",
    "prototypeType": "Material Test",
    "material": "Coral-Aggregate Concrete",
    "fabricationMethod": "Cast in Reusable Mold",
    "projectPhase": "Concept Study",
    "description": "Early-stage compressive testing of a coral-derived aggregate mix intended to reduce embodied carbon relative to standard aggregate.",
    "introduction": "Material research into locally sourced coral aggregate as a lower-carbon substitute in coastal cultural building construction.",
    "accessionNumber": "ARCH.2022.0501.01",
    "orbitCenterId": "center-material",
    "year": 2022,
    "orbitRadius": 100,
    "orbitAngleDeg": -40,
    "importance": 3
  },
  {
    "id": "hks-0512-mia-cul",
    "archiveCode": "HKS-0512-MIA-CUL",
    "title": "Salt-Fog Corrosion Panel",
    "location": "Miami, USA",
    "locationCode": "MIA-CUL",
    "typology": "Cultural",
    "prototypeType": "Material Test",
    "material": "Marine-Grade Aluminum",
    "fabricationMethod": "Accelerated Weathering Chamber",
    "projectPhase": "Field Trial",
    "description": "Accelerated salt-fog exposure test comparing anodized finish longevity across three aluminum alloy samples.",
    "introduction": "Corrosion-resistance study supporting facade metal selection for a coastal cultural institution.",
    "accessionNumber": "ARCH.2022.0512.01",
    "orbitCenterId": "center-material",
    "year": 2022,
    "orbitRadius": 190,
    "orbitAngleDeg": -5,
    "importance": 2
  },
  {
    "id": "hks-0620-hou-com",
    "archiveCode": "HKS-0620-HOU-COM",
    "title": "Mycelium Insulation Block",
    "location": "Houston, USA",
    "locationCode": "HOU-COM",
    "typology": "Commercial",
    "prototypeType": "Material Test",
    "material": "Mycelium Composite",
    "fabricationMethod": "Grown Formwork Casting",
    "projectPhase": "Concept Study",
    "description": "A grown mycelium block cured in reusable formwork, evaluated for thermal resistance against mineral wool baselines.",
    "introduction": "Speculative bio-based insulation study exploring grown materials as an alternative to petrochemical insulation.",
    "accessionNumber": "ARCH.2023.0620.01",
    "orbitCenterId": "center-material",
    "year": 2023,
    "orbitRadius": 280,
    "orbitAngleDeg": 35,
    "importance": 4
  },
  {
    "id": "hks-0733-den-off",
    "archiveCode": "HKS-0733-DEN-OFF",
    "title": "Recycled Glass Terrazzo Tile",
    "location": "Denver, USA",
    "locationCode": "DEN-OFF",
    "typology": "Office",
    "prototypeType": "Material Test",
    "material": "Recycled Glass Terrazzo",
    "fabricationMethod": "Cast and Ground Finish",
    "projectPhase": "Prototype (TRL-6)",
    "description": "Post-consumer glass terrazzo tile sample developed to match a specified reflectance and aggregate distribution.",
    "introduction": "Flooring material study for an office lobby using regionally sourced recycled glass aggregate.",
    "accessionNumber": "ARCH.2019.0733.01",
    "orbitCenterId": "center-material",
    "year": 2019,
    "orbitRadius": 130,
    "orbitAngleDeg": 130,
    "importance": 2
  },
  {
    "id": "hks-0844-lax-med",
    "archiveCode": "HKS-0844-LAX-MED",
    "title": "Antimicrobial Surface Coating Trial",
    "location": "Los Angeles, USA",
    "locationCode": "LAX-MED",
    "typology": "Medical / Research Facility",
    "prototypeType": "Material Test",
    "material": "Copper-Ion Coating",
    "fabricationMethod": "Vapor Deposition",
    "projectPhase": "Field Trial",
    "description": "A copper-ion coated handrail sample tested in a live clinical corridor for six months to measure surface contact contamination.",
    "introduction": "Companion material study to the Lattice Vault program, testing antimicrobial surface treatments for high-touch medical surfaces.",
    "accessionNumber": "ARCH.2021.0844.01",
    "orbitCenterId": "center-material",
    "year": 2021,
    "orbitRadius": 320,
    "orbitAngleDeg": -75,
    "importance": 3
  },
  {
    "id": "hks-0399-atl-air",
    "archiveCode": "HKS-0399-ATL-AIR",
    "title": "Modular Concourse Bay Study",
    "location": "Atlanta, USA",
    "locationCode": "ATL-AIR",
    "typology": "Transportation",
    "prototypeType": "Spatial Configuration Study",
    "material": "Steel Frame / Glass",
    "fabricationMethod": "Prefabricated Assembly",
    "projectPhase": "Design Development Study",
    "description": "A repeatable concourse bay module tested for passenger flow capacity under varied gate-adjacency configurations.",
    "introduction": "Typological study of a repeatable airport concourse bay intended to standardize future terminal expansions.",
    "accessionNumber": "ARCH.2018.0399.03",
    "orbitCenterId": "center-typology",
    "year": 2018,
    "orbitRadius": 110,
    "orbitAngleDeg": -60,
    "importance": 4
  },
  {
    "id": "hks-0455-phx-hos",
    "archiveCode": "HKS-0455-PHX-HOS",
    "title": "Patient Room Layout Variant C",
    "location": "Phoenix, USA",
    "locationCode": "PHX-HOS",
    "typology": "Medical / Research Facility",
    "prototypeType": "Spatial Configuration Study",
    "material": "N/A \\u2014 Planning Study",
    "fabricationMethod": "Full-Scale Mockup",
    "projectPhase": "Prototype (TRL-4)",
    "description": "A full-scale mockup room used to evaluate caregiver travel distance across three headwall configurations.",
    "introduction": "One of several patient room typology variants mocked up at full scale to test clinical workflow efficiency.",
    "accessionNumber": "ARCH.2020.0455.03",
    "orbitCenterId": "center-typology",
    "year": 2020,
    "orbitRadius": 210,
    "orbitAngleDeg": 10,
    "importance": 3
  },
  {
    "id": "hks-0512-dal-edu",
    "archiveCode": "HKS-0512-DAL-EDU",
    "title": "Flexible Classroom Cluster",
    "location": "Dallas, USA",
    "locationCode": "DAL-EDU",
    "typology": "Education",
    "prototypeType": "Spatial Configuration Study",
    "material": "Demountable Partition System",
    "fabricationMethod": "Modular Prefabrication",
    "projectPhase": "Prototype (TRL-6)",
    "description": "A cluster of four classrooms sharing a demountable partition system, reconfigured over a semester to test acoustic and layout performance.",
    "introduction": "A study of reconfigurable classroom clusters intended to extend the usable life of an education building typology.",
    "accessionNumber": "ARCH.2019.0512.02",
    "orbitCenterId": "center-typology",
    "year": 2019,
    "orbitRadius": 275,
    "orbitAngleDeg": 95,
    "importance": 3
  },
  {
    "id": "hks-0688-chi-off",
    "archiveCode": "HKS-0688-CHI-OFF",
    "title": "Core-to-Facade Ratio Study",
    "location": "Chicago, USA",
    "locationCode": "CHI-OFF",
    "typology": "Office",
    "prototypeType": "Massing Study",
    "material": "N/A \\u2014 Planning Study",
    "fabricationMethod": "Digital Massing Model",
    "projectPhase": "Concept Study",
    "description": "A comparative massing exercise testing daylight autonomy against five core-to-facade ratio scenarios for a speculative office tower.",
    "introduction": "An early massing study exploring the relationship between floorplate depth and daylight performance.",
    "accessionNumber": "ARCH.2021.0688.01",
    "orbitCenterId": "center-typology",
    "year": 2021,
    "orbitRadius": 150,
    "orbitAngleDeg": 200,
    "importance": 2
  },
  {
    "id": "hks-0217-dfw-spt-b",
    "archiveCode": "HKS-0217-DFW-SPT-B",
    "title": "Doubly-Curved Panel Grid",
    "location": "Dallas, USA",
    "locationCode": "DFW-SPT",
    "typology": "Sports Venue",
    "prototypeType": "Geometry Study",
    "material": "Aluminum Composite Panel",
    "fabricationMethod": "5-Axis CNC Milling",
    "projectPhase": "Design Development Study",
    "description": "A panelization strategy minimizing unique mold counts across a doubly-curved canopy surface.",
    "introduction": "Companion geometry study to the stadium canopy program, focused on panel rationalization for cost efficiency.",
    "accessionNumber": "ARCH.2021.0217.05",
    "orbitCenterId": "center-geometry",
    "year": 2021,
    "orbitRadius": 120,
    "orbitAngleDeg": -30,
    "importance": 3
  },
  {
    "id": "hks-0912-lon-cul",
    "archiveCode": "HKS-0912-LON-CUL",
    "title": "Voronoi Facade Screen Sample",
    "location": "London, UK",
    "locationCode": "LON-CUL",
    "typology": "Cultural",
    "prototypeType": "Geometry Study",
    "material": "GFRC",
    "fabricationMethod": "CNC-Cut Formwork",
    "projectPhase": "Prototype (TRL-4)",
    "description": "A cellular shading screen pattern generated from a weighted Voronoi field, tuned for solar performance at a specific latitude.",
    "introduction": "Parametric shading screen study developed for a cultural building facade with variable solar exposure.",
    "accessionNumber": "ARCH.2020.0912.02",
    "orbitCenterId": "center-geometry",
    "year": 2020,
    "orbitRadius": 220,
    "orbitAngleDeg": 20,
    "importance": 4
  },
  {
    "id": "hks-1044-tor-res",
    "archiveCode": "HKS-1044-TOR-RES",
    "title": "Folded Plate Roof Model",
    "location": "Toronto, Canada",
    "locationCode": "TOR-RES",
    "typology": "Residential",
    "prototypeType": "Geometry Study",
    "material": "Cross-Laminated Timber",
    "fabricationMethod": "CNC Panel Cutting",
    "projectPhase": "Prototype (TRL-6)",
    "description": "A folded-plate timber roof geometry tested for span efficiency using origami-derived crease patterns.",
    "introduction": "Structural geometry study applying folded-plate principles to a mass-timber residential roof structure.",
    "accessionNumber": "ARCH.2022.1044.01",
    "orbitCenterId": "center-geometry",
    "year": 2022,
    "orbitRadius": 300,
    "orbitAngleDeg": 150,
    "importance": 3
  },
  {
    "id": "hks-1188-sea-edu",
    "archiveCode": "HKS-1188-SEA-EDU",
    "title": "Robotic Assembly for Complex Geometry",
    "location": "Seattle, USA",
    "locationCode": "SEA-EDU",
    "typology": "Education",
    "prototypeType": "Experimental Fabrication Study",
    "material": "Timber / Steel Hybrid",
    "fabricationMethod": "Robotic Assembly",
    "projectPhase": "Prototype (TRL-6)",
    "description": "An extension of the education campus assembly study, testing non-repeating node geometries beyond the original structural grid.",
    "introduction": "Geometry-focused counterpart to the fabrication cluster\\u2019s robotic assembly research, sharing the same campus program.",
    "accessionNumber": "ARCH.2020.1188.02",
    "orbitCenterId": "center-geometry",
    "year": 2020,
    "orbitRadius": 60,
    "orbitAngleDeg": -120,
    "importance": 5
  }
];
const relationships = [
  {
    "source": "hks-0842-lax-med",
    "target": "hks-0844-lax-med",
    "category": "Typology",
    "description": "Both developed for the same medical research facility program in Los Angeles.",
    "strength": 0.8
  },
  {
    "source": "hks-0842-lax-med",
    "target": "hks-1215-ord-res",
    "category": "Fabrication",
    "description": "Shared reliance on large-scale robotic concrete extrusion techniques.",
    "strength": 0.65
  },
  {
    "source": "hks-0658-sea-edu",
    "target": "hks-0659-sea-edu",
    "category": "Fabrication",
    "description": "Sequential iterations of the same node connector research thread.",
    "strength": 0.9
  },
  {
    "source": "hks-0658-sea-edu",
    "target": "hks-1188-sea-edu",
    "category": "Project Phase",
    "description": "Parallel studies for the same education campus structural program.",
    "strength": 0.75
  },
  {
    "source": "hks-0217-dfw-spt",
    "target": "hks-0217-dfw-spt-b",
    "category": "Geometry",
    "description": "Panelization strategy developed directly from the canopy stress model.",
    "strength": 0.85
  },
  {
    "source": "hks-1093-sfo-cmx",
    "target": "hks-0733-den-off",
    "category": "Material",
    "description": "Both examine reclaimed or recycled material sourcing strategies.",
    "strength": 0.4
  },
  {
    "source": "hks-0501-mia-cul",
    "target": "hks-0620-hou-com",
    "category": "Material",
    "description": "Shared focus on lower-carbon, bio-derived material substitutes.",
    "strength": 0.55
  },
  {
    "source": "hks-0512-mia-cul",
    "target": "hks-0844-lax-med",
    "category": "Fabrication",
    "description": "Related accelerated exposure testing methodologies.",
    "strength": 0.35
  },
  {
    "source": "hks-0399-atl-air",
    "target": "hks-0512-dal-edu",
    "category": "Typology",
    "description": "Comparable modular, repeatable spatial bay strategies.",
    "strength": 0.45
  },
  {
    "source": "hks-0455-phx-hos",
    "target": "hks-0842-lax-med",
    "category": "Typology",
    "description": "Both support medical facility programs within the same research track.",
    "strength": 0.5
  },
  {
    "source": "hks-0912-lon-cul",
    "target": "hks-0501-mia-cul",
    "category": "Typology",
    "description": "Cultural building program overlap across differing climates.",
    "strength": 0.3
  },
  {
    "source": "hks-1044-tor-res",
    "target": "hks-1215-ord-res",
    "category": "Geometry",
    "description": "Both test self-supporting structural geometries to reduce material use.",
    "strength": 0.5
  },
  {
    "source": "hks-0688-chi-off",
    "target": "hks-0912-lon-cul",
    "category": "Geometry",
    "description": "Shared use of parametric performance modeling in early design study.",
    "strength": 0.4
  },
  {
    "source": "hks-0910-bos-lab",
    "target": "hks-0733-den-off",
    "category": "Project Phase",
    "description": "Both reached full prototype status within the same fiscal year.",
    "strength": 0.3
  }
];
const orbitCenters = [
  {
    "id": "center-fabrication",
    "label": "Fabrication Systems",
    "x": 260,
    "y": 610,
    "maxRadius": 420,
    "ringCount": 5
  },
  {
    "id": "center-material",
    "label": "Material Research",
    "x": 1030,
    "y": 230,
    "maxRadius": 340,
    "ringCount": 4
  },
  {
    "id": "center-typology",
    "label": "Typological Studies",
    "x": 820,
    "y": 800,
    "maxRadius": 290,
    "ringCount": 4
  },
  {
    "id": "center-geometry",
    "label": "Geometry Experiments",
    "x": 1440,
    "y": 570,
    "maxRadius": 330,
    "ringCount": 4
  }
];

const state={view:'observatory',selected:null,scale:.78,x:0,y:0,dragging:false,lastX:0,lastY:0,filters:new Set(['Material','Fabrication','Typology','Geometry','Project Phase'])};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const centerMap=Object.fromEntries(orbitCenters.map(c=>[c.id,c]));
archiveItems.forEach(item=>{const c=centerMap[item.orbitCenterId];const a=item.orbitAngleDeg*Math.PI/180;item.x=c.x+Math.cos(a)*item.orbitRadius;item.y=c.y+Math.sin(a)*item.orbitRadius});
$('#itemCount').textContent=`${String(archiveItems.length).padStart(3,'0')} OBJECTS`;
function setView(name){state.view=name;$$('.view').forEach(v=>v.classList.toggle('active-view',v.id===name));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));closeDetail();}
$$('[data-view]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();setView(el.dataset.view)}));
function applyTransform(){const t=`translate(${state.x}px,${state.y}px) scale(${state.scale})`;$('#orbitSvg').style.transform=t;$('#nodesLayer').style.transform=t;}
function svgEl(tag,attrs={}){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function renderObservatory(){const svg=$('#orbitSvg'), layer=$('#nodesLayer');svg.innerHTML='';layer.innerHTML='';
 relationships.forEach(r=>{const a=archiveItems.find(i=>i.id===r.source),b=archiveItems.find(i=>i.id===r.target);if(!a||!b)return;svg.appendChild(svgEl('line',{x1:a.x,y1:a.y,x2:b.x,y2:b.y,class:'relationship-line'}))});
 orbitCenters.forEach(c=>{for(let i=1;i<=c.ringCount;i++){const rad=c.maxRadius*i/c.ringCount;svg.appendChild(svgEl('circle',{cx:c.x,cy:c.y,r:rad,class:'orbit'}))}svg.appendChild(svgEl('circle',{cx:c.x,cy:c.y,r:8,class:'orbit-center'}));const tx=svgEl('text',{x:c.x+16,y:c.y-14,class:'orbit-label'});tx.textContent=c.label;svg.appendChild(tx)});
 archiveItems.forEach(item=>{const node=document.createElement('button');node.className='node';node.dataset.id=item.id;const size=16+item.importance*6;Object.assign(node.style,{left:item.x+'px',top:item.y+'px',width:size+'px',height:size+'px'});node.setAttribute('aria-label',item.title);const label=document.createElement('span');label.className='node-label';label.textContent=item.title;node.appendChild(label);node.addEventListener('click',e=>{e.stopPropagation();openDetail(item.id)});layer.appendChild(node)});applyTransform()}
function openDetail(id){state.selected=id;$$('.node').forEach(n=>n.classList.toggle('selected',n.dataset.id===id));const i=archiveItems.find(x=>x.id===id);if(!i)return;$('#detailContent').innerHTML=`<div class="detail-inner"><div class="detail-code">${i.archiveCode}</div><h2>${i.title}</h2><div class="detail-sub">${i.year} · ${i.location}</div><div class="image-placeholder"></div><p class="detail-description">${i.introduction}</p><div class="meta">${[['Accession',i.accessionNumber],['Typology',i.typology],['Prototype',i.prototypeType],['Material',i.material],['Fabrication',i.fabricationMethod],['Phase',i.projectPhase]].map(([a,b])=>`<div class="meta-row"><span>${a}</span><span>${b}</span></div>`).join('')}</div></div>`;$('#detailPanel').classList.add('open');$('#detailPanel').setAttribute('aria-hidden','false')}
function closeDetail(){state.selected=null;$$('.node').forEach(n=>n.classList.remove('selected'));$('#detailPanel').classList.remove('open');$('#detailPanel').setAttribute('aria-hidden','true')}
$('#closeDetail').onclick=closeDetail;
const canvas=$('#canvas');canvas.addEventListener('pointerdown',e=>{if(e.target.closest('.node'))return;state.dragging=true;state.lastX=e.clientX;state.lastY=e.clientY;canvas.classList.add('dragging');canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!state.dragging)return;state.x+=e.clientX-state.lastX;state.y+=e.clientY-state.lastY;state.lastX=e.clientX;state.lastY=e.clientY;applyTransform()});canvas.addEventListener('pointerup',()=>{state.dragging=false;canvas.classList.remove('dragging')});canvas.addEventListener('wheel',e=>{e.preventDefault();const old=state.scale;state.scale=Math.min(1.8,Math.max(.35,state.scale*(e.deltaY<0?1.08:.92)));const rect=canvas.getBoundingClientRect(),mx=e.clientX-rect.left-rect.width/2,my=e.clientY-rect.top-rect.height/2;state.x=mx-(mx-state.x)*(state.scale/old);state.y=my-(my-state.y)*(state.scale/old);applyTransform()},{passive:false});
$('#zoomIn').onclick=()=>{state.scale=Math.min(1.8,state.scale*1.15);applyTransform()};$('#zoomOut').onclick=()=>{state.scale=Math.max(.35,state.scale/1.15);applyTransform()};$('#zoomReset').onclick=()=>{state.scale=.78;state.x=0;state.y=0;applyTransform()};
function renderFilters(){const cats=['Material','Fabrication','Typology','Geometry','Project Phase'];$('#relationshipFilters').innerHTML=cats.map(c=>`<label class="filter-option"><input type="checkbox" checked value="${c}"><span>${c}</span></label>`).join('');$$('#relationshipFilters input').forEach(i=>i.onchange=()=>{i.checked?state.filters.add(i.value):state.filters.delete(i.value);renderRelationships()})}
function renderRelationships(){const visible=relationships.filter(r=>state.filters.has(r.category));$('#relationshipGraph').innerHTML=visible.map(r=>{const a=archiveItems.find(i=>i.id===r.source),b=archiveItems.find(i=>i.id===r.target);return `<article class="relationship-card" data-id="${a.id}"><div class="category">${r.category}</div><h3>${a.title} ↔ ${b.title}</h3><p>${r.description}</p><div class="strength"><span style="width:${r.strength*100}%"></span></div></article>`}).join('')||'<p>No relationship categories selected.</p>';$$('.relationship-card').forEach(c=>c.onclick=()=>{setView('observatory');openDetail(c.dataset.id)})}
function renderTimeline(){const years=[...new Set(archiveItems.map(i=>i.year))].sort((a,b)=>b-a);$('#timelineList').innerHTML=years.map(y=>`<section class="year-group"><div class="year-label">${y}</div><div class="year-items">${archiveItems.filter(i=>i.year===y).map(i=>`<article class="timeline-item" data-id="${i.id}"><small>${i.archiveCode}</small><h3>${i.title}</h3><p>${i.location} · ${i.material}</p></article>`).join('')}</div></section>`).join('');$$('.timeline-item').forEach(c=>c.onclick=()=>{setView('observatory');openDetail(c.dataset.id)})}
function openSearch(){const o=$('#searchOverlay');o.classList.add('open');o.setAttribute('aria-hidden','false');$('#searchInput').value='';renderSearch('');setTimeout(()=>$('#searchInput').focus(),30)}function closeSearch(){const o=$('#searchOverlay');o.classList.remove('open');o.setAttribute('aria-hidden','true')}
function renderSearch(q){q=q.toLowerCase().trim();const res=archiveItems.filter(i=>!q||[i.title,i.material,i.location,i.typology,i.archiveCode].join(' ').toLowerCase().includes(q)).slice(0,20);$('#searchResults').innerHTML=res.map(i=>`<div class="search-result" data-id="${i.id}"><small>${i.archiveCode}</small><strong>${i.title}</strong><span>${i.year} · ${i.location}</span></div>`).join('');$$('.search-result').forEach(r=>r.onclick=()=>{closeSearch();setView('observatory');openDetail(r.dataset.id)})}
$('#searchButton').onclick=openSearch;$('#closeSearch').onclick=closeSearch;$('#searchInput').oninput=e=>renderSearch(e.target.value);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeSearch();closeDetail()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}});
renderObservatory();renderFilters();renderRelationships();renderTimeline();
